name = "mahesh-portfolio-worker"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[vars]
BUCKET_NAME = "mahesh-portfolio-media"
PUBLIC_MEDIA_DOMAIN = ""

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "mahesh-portfolio-media"
